import type { Metadata } from "next";
import { Navbar } from "@/stories/components/navbar/Index";
import "@/app/globals.scss";
import { Footer } from "@/stories/components/footer/Index";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const footerArgs = {
  links: [
    { label: "Contact Us", url: "/contact" },
    { label: "Privacy Policy", url: "/privacy" },
    { label: "Terms of Service", url: "/terms" },
  ],
  socialLinks: [
    { label: "Facebook", url: "https://facebook.com" },
    { label: "Twitter", url: "https://twitter.com" },
    { label: "LinkedIn", url: "https://linkedin.com" },
    { label: "GitHub", url: "https://github.com" },
    { label: "Instagram", url: "https://instagram.com" },
  ],
  logo: {
    src: "/logo.svg",
    alt: "Logo",
  },
  copyright: `© ${new Date().getFullYear()} Accipiter Tech Consulting. All rights
        reserved.`,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="page-body">
        <Navbar />
        {children}
        <Footer {...footerArgs} />
      </body>
    </html>
  );
}
