import type { Metadata } from "next";
import { Navbar } from "@/stories/components/navbar/Index";
import { Primary as NavbarArgs } from "@/stories/components/navbar/Index.stories";
import "@/app/globals.scss";
import { Footer } from "@/stories/components/footer/Index";
import {Primary as FooterArgs } from "@/stories/components/footer/Index.stories";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="page-body">
        <Navbar {...NavbarArgs.args} />
        {children}
        <Footer {...FooterArgs.args} />
      </body>
    </html>
  );
}
